### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Dissociable**
- Fix not Finishing Magic Item Purchase
- Detect Maintenance Break Finished and Reload Game

### CODE REVIEW

**Comment by boludoz** [comment]
don't forget to add the 1 in the random (x, x, 1).

**Comment by boludoz** [comment]
It is an excellent commit, trying to solve the problem of the order of the troops.

**Comment by boludoz** [comment]
You can pass me your email so I add you to a slack working group and avoid confusion.

**Comment by Dissociable** [comment]
> 
> 
> You can pass me your email so I add you to a slack working group and avoid confusion.

Sent you in Mybot.run forum.

**Pull request merged**
