### PR TITLE
Temp fixes

### PR DESCRIPTION
**Pull request by vDrag0n**
-add arrayrandomshuffle to the include files.

### CODE REVIEW

**Comment by Dissociable** [comment]
_ArrayRandomShuffle? Sorry?
Why not just use _ArraySuffle?
You used an snippet that's been coded in 2010 and now we can use _ArrayShuffle because it's been added to AutoIt in 2014.

**Comment by boludoz** [comment]
> _ArrayRandomShuffle? Sorry?
> Why not just use [_ArraySuffle](https://www.autoitscript.com/autoit3/docs/libfunctions/_ArrayShuffle.htm)?
> That snippet coded in 2010 and now we can use [_ArrayShuffle](https://www.autoitscript.com/autoit3/docs/libfunctions/_ArrayShuffle.htm) because AutoIt has it since 2014.

Sorry, @vDrag0n comes from other languages, thanks for the noted detail.

**Comment by boludoz** [comment]
@vDragon is a good very detailed programmer, at first @vDragon used _ArrayShuffle, then for a reason I use this function, maybe have some reason to do it. 
If you would like to speak to us, please email us and I will send you an invitation from the Slack app.

**Comment by vDrag0n** [comment]
I wasn't able to deploy when using _ArrayShuffle.  Are there any flags that need to be added besides just _ArrayShuffle with array items?

**Comment by Dissociable** [comment]
> 
> 
> I wasn't able to deploy when using _ArrayShuffle. Are there any flags that need to be added besides just _ArrayShuffle with array items?

If you mean parameters, You can use _ArrayShuffle just like:
`_ArrayShuffle($anArray)`



> 
> 
> @Vdragon is a good very detailed programmer, at first @Vdragon used _ArrayShuffle, then for a reason I use this function, maybe have some reason to do it.
> If you would like to speak to us, please email us and I will send you an invitation from the Slack app.
> I notice that it may be a more purpose-optimized function maybe.

Don't have your email.

**Comment by vDrag0n** [comment]
`	$newPixelBottomRight = _ArrayRandomShuffle(GetVectorPixelOnEachSide2($newPixelBottomRight, 0, $slotsPerEdge))
	_ArrayDisplay($newPixelBottomRight)
	$newPixelBottomRight = _ArrayShuffle(GetVectorPixelOnEachSide2($newPixelBottomRight, 0, $slotsPerEdge))
	_ArrayDisplay($newPixelBottomRight)`
_ArrayRandomShuffle
image
_ArrayShuffle
image

**Comment by Dissociable** [comment]
@vDrag0n What?! you mean ArrayShuffle just delete and the result missing some indexes?! Impossible

Just to make you sure:
test au3

**Comment by vDrag0n** [comment]
You're right it doesn't remove index (Running GetVectorPixelOnEachSide2 twice will change coordinates).  

Unfortunately, I am still unable to deploy on the side that uses _ArrayShuffle instead of _ArraryRandomShuffle.

If you are able to deploy using _ArrayShuffle, let me know.

**Comment by boludoz** [comment]
Comments added via cherry pick.

**Pull request closed without merging**
